# Generated by Django 3.0.5 on 2020-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200501_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='vclient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='vserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=19)),
            ],
        ),
    ]
