# Generated by Django 3.0.5 on 2020-05-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vclient_vserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='bigpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppicon', models.ImageField(upload_to='')),
                ('pptitle', models.CharField(max_length=75)),
                ('ppdetails', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'bigpp',
            },
        ),
        migrations.DeleteModel(
            name='vclient',
        ),
        migrations.DeleteModel(
            name='vserver',
        ),
    ]
