# Generated by Django 3.0.5 on 2020-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200504_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigpp',
            name='ppicon',
            field=models.ImageField(default='https://images.unsplash.com/photo-1527683611643-4009f3a76197?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', upload_to='images/'),
        ),
    ]
