# Generated by Django 3.0.5 on 2020-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bigpp_ppcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigpp',
            name='ppdetails',
            field=models.TextField(max_length=200),
        ),
    ]
