# Generated by Django 3.0.5 on 2020-05-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200504_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'contact_forms',
            },
        ),
    ]
