# Generated by Django 3.0.5 on 2020-05-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_form',
        ),
    ]
