# Generated by Django 3.0.5 on 2020-05-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_supp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supp',
        ),
    ]
