# Generated by Django 3.0.5 on 2020-05-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Cimage',
            field=models.ImageField(default='https://images.unsplash.com/photo-1527683611643-4009f3a76197?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='series',
            name='Simage',
            field=models.ImageField(default='https://images.unsplash.com/photo-1527683611643-4009f3a76197?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', upload_to='images/'),
        ),
    ]
