# Generated by Django 3.0.5 on 2020-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_skills_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='sno',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
